### ISSUE TITLE
Build Error:  //go:build comment without // +build comment (exit status 1)

### ISSUE THREAD

**Issue by xudoo7** [bitfield/script#131]
I try to run the example of following on windows 11 system.

package main

import (
	"github.com/bitfield/script"
)

func main() {
	script.Stdin().Column(1).Freq().First(10).Stdout()
}

 I get an error,when I run it:

Build Error: go build -o d:\work\code\goProject\src\shell\__debug_bin.exe -gcflags all=-N -l .
main.go:4:2: //go:build comment without // +build comment (exit status 1)

How cloud I  fix it ？ 
Thank you

**Comment by bitfield** [comment]
Hi @xudoo7! Thanks for the bug report. Could you tell us the result of running `go version`, please?

**Comment by xudoo7** [comment]
thank you for reply . @bitfield 
my go version is 1.16

**Comment by bitfield** [comment]
Thanks @xudoo7. The error that you're seeing is because a new build tag syntax was introduced in Go 1.17, so if you're able to upgrade to at least that version (but preferably Go 1.19, which is the current stable release), you should be able to build the project with no issues.

Let me know if this doesn't fix the problem.

**Comment by xudoo7** [comment]
it works. @bitfield  thank you 
i update the go 1.16 to 1.19. all examples are works. nice.

**Comment by hacker1409** [comment]
My doubts have finally been resolved, thank you
