### ISSUE TITLE
ExecForEach does not return error

### ISSUE THREAD

**Issue by matesitox** [bitfield/script#142]
If I execute this on ubuntu 22.04
```	
p := script.Echo("a\nb\nc\n").ExecForEach("ls {{.}}")
p.Wait()
fmt.Println(p.Error())
```
I get:
```
<nil>
```
Even though the files "a", "b", and "c" do not exist and the command `'ls a` results in a non-zero exit status.

I was expecting an error to be printed. What am I doing wrong?

**Comment by bitfield** [comment]
Because `ExecForEach` runs a _bunch_ of commands, it doesn't set the pipe's error status if any _one_ of those commands fails. Instead, it just prints the error message to the pipe and carries on.

However, `p.Wait` discards all the pipe's output, which is why you're not seeing the error messages. Try something like:

```go
script.Echo("a\nb\nc\n").ExecForEach("ls {{.}}").Stdout()
// Output:
// ls: a: No such file or directory
// exit status 1
// ls: b: No such file or directory
// exit status 1
// ls: c: No such file or directory
// exit status 1
```

**Comment by matesitox** [comment]
Thanks for the explanation!
