### ISSUE TITLE
Add Base64 encode and decode methods

### ISSUE THREAD

**Issue by malisetti** [bitfield/script#181]

**Comment by bitfield** [comment]
Hi @malisetti! Thanks for opening the issue. Could you give us a sample program showing some code that you'd like to write using this feature?

**Comment by alex-vsl** [comment]
@bitfield In my opinion this is very handy for sure- especialy in k8s ecosystem, where secrets are usually base64-encoded. 

bash with kubectl:
```bash
kubectl get secret my-secret -o=jsonpath='{.data.myfield}' | base64 --decode
```

It's not hard to image how that could be used in conjuction with `Exec()` and `JQ`:
```go
secretSpecificField := script.Exec("kubectl get secret --output json --namespace XYZ some-secret").JQ(".data.myfield").Base64Decode()
```

And vice versa- you might want to perform base64 encoding while setting some value. 
What is more, base64 is widely used across the web, for instance sometimes HTML | CSS | JS values in the DOM Tree are encoded in base64

**Comment by bitfield** [comment]
That sounds totally reasonable. But your example program:

```go
secretField := script.Exec("kubectl ...").JQ(".data.myfield").Base64Decode().String()
```

doesn't actually match the API in #182, which is:

```go
func (p *Pipe) Base64Encode(enc *base64.Encoding) (string, error) {
```

In other words, `Base64Encode`, as implemented, returns `string` and `error`, rather than a pipe. I think making it a filter works better, don't you? For example, you might want to pass the base64-encoded data to some other command via `Exec`, or just do some further pipe filtering on it.

Also, in case we want to encode/decode other formats as well as base64, perhaps we should name the method `EncodeBase64` instead of `Base64Encode`. What do you think?

It seems a shame to make users pass a `*base64.Encoding` as a mandatory parameter. That sounds like paperwork, doesn't it? Would it be more in the spirit of `script` to assume the user wants `base64.StdEncoding` by default?

What do you think about changing the PR to adopt an API something like this?

```go
func (p *Pipe) EncodeBase64() *Pipe {
```

**Comment by mahadzaryab1** [comment]
@bitfield are you looking for someone to work on this? this seems like fun and i'd like to take it on if we're good to move forward with it

**Comment by bitfield** [comment]
There is already a PR open for this, which you're welcome to take forward if you like, or you could start from scratch—either way is fine.

**Comment by mahadzaryab1** [comment]
@bitfield opened a new PR https://github.com/bitfield/script/pull/210

**Comment by bitfield** [comment]
Thanks @mahadzaryab1! @malisetti and and @alex-vsl, would you like to try this with your use cases? (`go get github.com/bitfield/script@10e8421`)
