### ISSUE TITLE
how to get the stdout of the Exec result?

### ISSUE THREAD

**Issue by moonsn** [bitfield/script#191]
I want get the "ls" command stdout to buf.

but this code doesn't work.
``` go
buf := new(bytes.Buffer)
p := script.NewPipe().WithStdout(buf).Exec("ls")
p.Wait()
// expect buf contains the result, but it's an empty string.
```

**Comment by bitfield** [comment]
Hi @moonsn, thanks for the problem report! I see where the confusion has arisen. You guessed that the output of any commands run by `Exec` would go to the pipe's configured standard output. And that's a completely reasonable assumption: it just turns out not to be the case.

In fact, the output of commands run by `Exec` always goes to the _pipe_, which makes sense when you remember that `script` is all about building pipelines. The program that does what you want is something more like this:

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/bitfield/script"
)

func main() {
	buf := new(bytes.Buffer)
	script.NewPipe().WithStdout(buf).Exec("echo hello").Stdout()
	fmt.Println(buf)
}
```
https://go.dev/play/p/wP3nJmr0BGQ

Does that help?

**Comment by moonsn** [comment]
@bitfield thanks for your help, the README.md says:
> If you do need to wait for the pipeline to complete, call [Wait](https://pkg.go.dev/github.com/bitfield/script#Pipe.Wait).

but the Wait "Sink" does not return a result. So if I want to get the "buf" after the Exec command is complete, I need to call Wait. but how to get the "output"?

**Comment by bitfield** [comment]
Well, any sink that reads the pipe to completion will have the same effect (`Stdout`, for example).
