### ISSUE TITLE
File/directory operations

### ISSUE THREAD

**Issue by bitfield** [bitfield/script#21]
It's common to need to do things like make directories, make symlinks, rename files, and so on in shell scripts. Even though it doesn't quite fit in with the pipe metaphor, it might still be useful to have convenience versions of these in `script`.

(Rename is an interesting case, as a direct `os.Rename` isn't allowed in overlay filesystems like Docker containers. You have to do a copy followed by delete, which is by no means straightforward. A Docker-safe rename tool would be useful.)

**Comment by bitfield** [comment]
So far I haven't managed to write a lot of programs using `script`, which is a shame—I really need to do more of this to get a feel for how the API works, or doesn't. I'll close this for now pending more specific suggestions.

**Comment by andriykrefer** [comment]
I think that would be a nice addition to the library. I just met "script" and did not have a chance to use it yet. But I really like the concept. The first thing that I saw missing was these file operations.

The file copy operation is also odd in go. Since you have to open a file, read it and write to a new file, instead of just calling a "Copy" function.

**Comment by bitfield** [comment]
Feel free to make some suggestions @andriykrefer! Ideally, provide a short program that solves a problem you have, using the `Copy` operation, for example. That'll help us get a sense of what a good API would look like.
