### ISSUE TITLE
Stream pipes

### ISSUE THREAD

**Issue by posener** [bitfield/script#34]
I really like the idea of this library and it might makes a lot of scripting tasks easy!

The current implementation read all output of each command into memory, and then passes it to the next command and so forth.

For example:
* The usage of [`CombinedOutput`](https://github.com/bitfield/script/blob/master/filters.go#L119) (Also not sure why it was chosen to use the combined output and not stdout?)
* The usage of [string builder in the ForEachLine](https://github.com/bitfield/script/blob/master/filters.go#L97).

It would be nice to avoid it if it is not necessery. Let each reader read as much as needed from previous stage and output whatever necessary to the next stage. This is also how pipes in bash works.

**Comment by posener** [comment]
I've re-written some of the functionality of this library with streaming enabled to explain better what I was thinking: https://github.com/posener/script.

**Comment by bitfield** [comment]
Sounds great! How about putting in a PR to this library to add the streaming functionality?

**Comment by posener** [comment]
Thanks! This is not new functionality but rather replacing the whole underlying mechanism...

**Comment by bitfield** [comment]
Fine! How about putting in a PR to replace the whole underlying mechanism?

**Comment by bitfield** [comment]
I think this is worth doing.

**Comment by kepkin** [comment]
any news on that?

**Comment by bitfield** [comment]
@kepkin it needs a little thought—are you having an issue with memory use?

**Comment by kepkin** [comment]
Well.. I see a totally different approach.

Bash is actually starts all programs in pipeline asynchronously. We can repeat that in go and get following bonuses:
 - low memory usage cause data is piped
 - faster execution as you don't need to accumulate data before passing it further
 - you can make fancy stuff like watch (see GIF in my repo)

Please check out:
https://github.com/kepkin/async-script/tree/master

**Comment by posener** [comment]
@kepkin check out https://github.com/posener/script that was inspired from this project, has similar functionality but was designed for streaming the data.

**Comment by bitfield** [comment]
It's interesting to see these efforts, but I do have the strong feeling that they're solving a problem which does not in fact exist (or, at any rate, they haven't demonstrated that a problem exists). In general, I prefer simple, natural, obvious design, even if that's inherently inefficient. Because the cost of complexity affects every single feature and every contributor to the project, now and in the future, I set a very high bar for making such changes.

For devops and sysadmin tasks, which I imagine is where the `script` library is most useful, performance is very rarely an issue. (I'd be delighted to see a counterexample, though.) 

If there's a way of adding simple, natural streaming functionality to the core of `script`, then I'll be in favour of it. I haven't seen anything so far which really appeals to me, but as an experienced programmer, I'm keenly aware of the limited size of my own head, which is why this issue is here to help track suggestions.

**Comment by kepkin** [comment]
I see. I'm not afraid of complexity and my needs are more for developers rather than sysadmins.
I'll try add exec functionality for https://github.com/ReactiveX/RxGo

**Comment by bitfield** [comment]
>  I'm not afraid of complexity

(in a Yoda voice) _You... will... be._
