### ISSUE TITLE
script.Exec().String() does not return the command output when the execution fails

### ISSUE THREAD

**Issue by unicolet** [bitfield/script#38]
This possibly happens in some cases only, where the exit code is some special number, but I can reproduce with a script like the following:

artificially lock the git repository
```sh
touch .git/index.lock
```

now try to run something like:
```go
var out, _ = script.Exec("git checkout master").String()
fmt.Println(out) // will be empty
```

`git checkout master` would have instead printed sthing like:

```
fatal: Unable to create '<path>/go/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
```

but that output is not easily accessible. A workaround I am using is to ignore the error status of the pipeline:

```go
var p = script.Exec("git checkout master")
var data, err = ioutil.ReadAll(p.Reader)
var out = string(data)
fmt.Println(out) // will contain the full output
```

I believe it should be enough to change https://github.com/bitfield/script/blob/master/sinks.go#L69 so that it returns whatever data it was able to read. I suspect the same (or similar) change should be made in [Bytes()](https://github.com/bitfield/script/blob/master/sinks.go#L21) as well.

I'd be happy to try and provide PR :-)

**Comment by bitfield** [comment]
Yes, I agree this is slightly confusing, although it's documented behaviour: https://github.com/bitfield/script#error-output

The reason is that all operations on an 'erroneous' pipe are no-ops, for safety. Suppose the first stage of a long pipeline causes an error. By definition, then, its output is not useful, and we don't want the remaining stages to operate on bogus results.

As you say, one workaround is to read directly from the pipe's Reader; another is to set the error status to nil. But I'd like to keep the current behaviour because it means you can't accidentally overlook an error and get bogus output.

**Comment by unicolet** [comment]
@bitfield oh, I missed the bit. I'd say then we can close, I agree it's better to err on the safe side. Thanks for you time and `script` :-) It's my first foray in `go`-land and so far liking it
