### ISSUE TITLE
FindFiles exits and returns no files when it can't open a directory

### ISSUE THREAD

**Issue by jreisinger** [bitfield/script#99]
This program

```
package main

import (
	"log"
	"os"

	"github.com/bitfield/script"
)

func main() {
	h, err := os.UserHomeDir()
	if err != nil {
		log.Fatal(err)
	}
	_, err = script.FindFiles(h).Stdout()
	if err != nil {
		log.Fatal(err)
	}
}
```

yields:

```
$ go build
$ ./script
2022/03/12 11:51:51 open /Users/user/.Trash: operation not permitted
```

I expected behavior similar to `find $HOME -type f`, i.e. to return files from directories it can open.

**Comment by bitfield** [comment]
Thanks, @jreisinger! Yes, that seems a reasonable expectation.

**Comment by bitfield** [comment]
It seems like FindFiles should just ignore any errors encountered by `filepath.Walk`. I think while we're working on that, it would make sense to update FindFiles to use [fs.WalkDir](https://pkg.go.dev/io/fs#WalkDir) instead of `filepath.Walk`, wouldn't it? Then it would be easier to test (see [Walking with filesystems](https://bitfieldconsulting.com/golang/filesystems)).

**Comment by parkerduckworth** [comment]
@bitfield agree that using `fs.WalkDir` with `fs.SkipDir` would provide a nice DX here. 

Thinking that we'd still want to include the permission errors in the output though (rather than completely swallowing), as this is more aligned with the default behavior of `find`?

Maybe checking to see if the [fs.WalkDirFunc](https://pkg.go.dev/io/fs#WalkDirFunc) returns `fs.ErrPermission`, and if so, append `<path-to-file>: permission denied` to [filenames](https://github.com/bitfield/script/blob/master/script.go#L224). Otherwise if any other err type is encountered, it should be piped out [WithError](https://github.com/bitfield/script/blob/master/script.go#L162).

The developer could always just [Reject](https://github.com/bitfield/script/blob/master/script.go#L648) lines containing  `"permission denied"` from the resulting pipe of a successful find.

**Comment by bitfield** [comment]
@parkerduckworth it's a tricky area, because one of the design goals for `script` is to just get out of your way so that you can cook up quick hacks, and in the event of errors it should just "do the right thing", without blocking your task.

**Comment by parkerduckworth** [comment]
Ah, ok. Understood

**Comment by bitfield** [comment]
Happy to accept PRs for this.

**Comment by parkerduckworth** [comment]
@bitfield great, just submitted one

**Comment by mahadzaryab1** [comment]
@bitfield what's the status of this? i'd be happy to pick it up if it still needs fixing

**Comment by bitfield** [comment]
@mahadzaryab1 I think this [question](https://github.com/bitfield/script/pull/122#issuecomment-1228594829) is still open about the design—what's your view?

**Comment by mahadzaryab1** [comment]
@bitfield that sounds good to me! PR open for review at https://github.com/bitfield/script/pull/217

**Comment by jreisinger** [comment]
As for switching from `filepath.Walk` to `fs.Walkdir` in https://github.com/bitfield/script/pull/217: shouldn't be the only reason for doing so easier testing? I mean using `fstest` instead of creating folders and files in `testdata`. @bitfield do you think the switch still makes sense even though the tests haven't been changed?

**Comment by bitfield** [comment]
@jreisinger as far as I know, there's no difference, hence no specific reason to change. It's just that if we were writing this function today, we would of course use the FS-based approach. And we _are_ writing it today, in a sense, so I'm fine with the change, unless you think there's a good reason _not_ to make it?
